apiVersion: v1
kind: Namespace
metadata:
  name: ai-reader
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db-pvc
  namespace: ai-reader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ai-reader
type: Opaque
data:
  OPENAI_API_KEY: "c2steW91ci1rZXk=" # echo -n 'sk-your-key' | base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ai-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/ai-reader-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: backend-secret
          volumeMounts:
            - name: db-storage
              mountPath: /app/articles.db
              subPath: articles.db
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: backend-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ai-reader
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ai-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/ai-reader-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ai-reader
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
