apiVersion: v1
kind: Namespace
metadata:
  name: ai-reader
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ai-reader
type: Opaque
data:
  OPENAI_API_KEY: c2st
  OPENAI_API_BASE: aHR0cHM
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ai-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: thunder   # 绑定到含该本地文件的 thunder 节点
      containers:
        - name: backend
          image: harbor.lulaide.com:80/ai-reader/ai-reader-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: backend-secret
          volumeMounts:
            - name: db-storage
              mountPath: /app/articles.db           # 容器内访问路径（文件）
      volumes:
        - name: db-storage
          hostPath:
            path: /root/AI-Reader/back/articles.db  # 宿主机真实文件
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ai-reader
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ai-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: harbor.lulaide.com:80/ai-reader/ai-reader-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ai-reader
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080