name: 构建和推送 Docker 镜像
on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.lulaide.com:80
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: |
            harbor.lulaide.com:80/ai-reader/ai-reader-backend:latest
            harbor.lulaide.com:80/ai-reader/ai-reader-backend:${{ gitea.sha }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.lulaide.com:80
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: |
            harbor.lulaide.com:80/ai-reader/ai-reader-frontend:latest
            harbor.lulaide.com:80/ai-reader/ai-reader-frontend:${{ gitea.sha }}
